name: release

on:
  push:
    branches:
      - 'release/**'

env:
  TF_VERSION: 0.12.26
  STACKS: "aaa bbb ccc"

jobs:
  ci:
    name: release
    runs-on: ubuntu-latest

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Pull code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare PR body
      run: |
        echo ::set-env name=body::$(git log master...${{ github.ref }} --oneline --no-decorate)

    - name: Create or update pull request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        source_branch: "${{ github.ref }}"
        pr_title: "Release: latest"
        pr_body: |
          A new release has been prepared:

          ${{ env.body }}
        pr_assignee: "github-actions"
        pr_reviewer: "/b2c,fedjabosnic"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
